### ISSUE TITLE
Can this be used on Windows 11

### ISSUE THREAD

**Issue by milkywaymw** [ebalo55/mimikatz#1]
Can sekurlsa::logonpasswords be used in Windows 11？

**Comment by ebalo55** [comment]
Yes, this is the UN-official build of mimilatz working on W11, source edits
are not mine, refer to the original pull request author on the official
mimilatz package for that.
Using this code you can easily build from source your version of mimilatz
executable (only tested with the executable as of now)

Il ven 3 nov 2023, 15:56 milkywaymw ***@***.***> ha scritto:

**Comment by milkywaymw** [comment]
Have you used pypykatz, does the python version work with Windows 11?

**Comment by ebalo55** [comment]
No, i've not, i don't know if that works sorry

Il ven 3 nov 2023, 17:11 milkywaymw ***@***.***> ha scritto:
